# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Bioinformatics Misadventures"
email: wkpalan@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
    The personal website of Kokulapalan Wimalanathan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wkpalan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gokool4bioinfo
github_username:  wkpalan

# Build settings
markdown: kramdown
theme: gokool
plugins:
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-sitemap


exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - LICENSE.txt
  - '*gemspec'
  - '*.sh'
  - 'site'

scholar:
  bibliography_template: bib
  style: american-physics-society
  sort_by: year, month
  order: descending
  group_by: year
  group_order: descending
  bibliography_template: bib
  bibliography_group_tag: h4
  bibliography_list_tag: 'div'
  bibliography_list_attributes:
    class: "pub-list"
  bibliography_item_tag: 'div'
  # bibliography_item_attributes:
  #    class: "mdl-cell mdl-cell--12-col pub-item"

jekyll_pubmed:
  - data: "publications"
    term: "Wimalanathan K"

#jekyll_get:
#  - data: publications
#    json: 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=26432828'
#    json: 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=Wimalanathan K&format=json'
